import type { Metadata } from "next";
import {Inter} from 'next/font/google'
import "./globals.css";
import "@/app/header"
import GlobalHeader from "@/app/header";

const interBold = Inter({
	weight:"700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interBold.className} antialiased`}
      >
				<GlobalHeader />
        {children}
      </body>
    </html>
  );
}
